"""
Derive the firmware version from git and expose it as FIRMWARE_VERSION.

    r46.1b09187            the 46th commit, clean working tree
    r46.1b09187+a3f9c21    the same commit, plus uncommitted changes

The leading count is `git rev-list --count HEAD`, which auto-increments per
commit without any state file to keep — so it survives the build container
being recreated, and is identical on every machine that has the repository.

The suffix after `+` is a fingerprint of the uncommitted changes. It exists
because most flashes during debugging are of a working tree that no commit
describes: without it the device would claim to be running committed code that
it is not. A fingerprint rather than a timestamp so that rebuilding the same
source twice yields the same version, and does not force a recompile.

Writes include/version.h rather than appending to CPPDEFINES: a define changes
the build signature for every source file in the project, so a version that
moves would rebuild the whole framework each time. The header is only rewritten
when its contents actually change.
"""

Import("env")

import hashlib
import os
import subprocess

HEADER_PATH = os.path.join(env["PROJECT_DIR"], "include", "version.h")

# What the firmware is actually built from. Changes anywhere else — notes,
# datasheets, editor settings — must not move the version.
BUILD_INPUTS = ("src", "include", "platformio.ini")


def git(*args):
    """Run a git command in the project directory, or raise."""
    return (
        subprocess.check_output(
            ["git"] + list(args),
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
        )
        .decode("utf-8", "replace")
        .strip()
    )


def compute_version():
    try:
        version = "r%s.%s" % (git("rev-list", "--count", "HEAD"),
                              git("rev-parse", "--short", "HEAD"))
    except Exception:
        # No git, no repository, or no commits yet. A build is still possible
        # and should not fail over version metadata.
        return "unknown"

    try:
        # `diff HEAD` covers modified tracked files including staged ones;
        # `status --porcelain` additionally catches files that are new or
        # deleted, whose content the diff would miss.
        #
        # Scoped to what actually ends up in the firmware. Unscoped, leaving a
        # stray file anywhere in the working tree changed the version, which
        # made it useless as an answer to "is the device running this code?".
        # Note this deliberately excludes the gitignored include/secrets.h:
        # reconfiguring WiFi does not change the program.
        changes = (git("diff", "HEAD", "--", *BUILD_INPUTS) +
                   git("status", "--porcelain", "--", *BUILD_INPUTS))
    except Exception:
        return version

    if changes:
        version += "+" + hashlib.sha1(changes.encode("utf-8")).hexdigest()[:7]

    return version


def write_header(path, version):
    content = (
        "// Generated by scripts/version.py on every build.\n"
        "// Not tracked by git, and not meant to be edited.\n"
        "#ifndef VERSION_H\n"
        "#define VERSION_H\n"
        '#define FIRMWARE_VERSION "%s"\n'
        "#endif // VERSION_H\n" % version
    )

    existing = None
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as handle:
            existing = handle.read()

    # Rewriting an unchanged header would update its mtime and rebuild every
    # translation unit that includes it, on every build.
    if existing != content:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)


version = compute_version()
write_header(HEADER_PATH, version)
print("Firmware version: %s" % version)
